from PyQt6 import QtCore, QtGui, QtWidgets
from for_number_characteristic import Number, NotNaturalNumberError, ToBigNumber


class NumberAnalysis(QtWidgets.QWidget):
    def __init__(self, parent):
        super().__init__(parent)
        self.setupUi(self)
        self.base_texts()
        self.connecting()
        self.last_number = None

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(407, 550)
        self.get_result_btn = QtWidgets.QPushButton(parent=Form)
        self.get_result_btn.setGeometry(QtCore.QRect(127, 110, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.get_result_btn.setFont(font)
        self.get_result_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.get_result_btn.setObjectName("get_result_btn")
        self.lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 20, 381, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(100, 50, 260, 16))
        self.label.setObjectName("label")
        self.scrollArea = QtWidgets.QScrollArea(parent=Form)
        self.scrollArea.setGeometry(QtCore.QRect(9, 149, 391, 391))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -559, 372, 948))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.count_of_numbers_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.count_of_numbers_label.sizePolicy().hasHeightForWidth())
        self.count_of_numbers_label.setSizePolicy(sizePolicy)
        self.count_of_numbers_label.setMinimumSize(QtCore.QSize(0, 30))
        self.count_of_numbers_label.setObjectName("count_of_numbers_label")
        self.verticalLayout.addWidget(self.count_of_numbers_label)
        self.amount_of_numbers_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amount_of_numbers_label.sizePolicy().hasHeightForWidth())
        self.amount_of_numbers_label.setSizePolicy(sizePolicy)
        self.amount_of_numbers_label.setMinimumSize(QtCore.QSize(0, 30))
        self.amount_of_numbers_label.setObjectName("amount_of_numbers_label")
        self.verticalLayout.addWidget(self.amount_of_numbers_label)
        self.product_of_numbers_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.product_of_numbers_label.sizePolicy().hasHeightForWidth())
        self.product_of_numbers_label.setSizePolicy(sizePolicy)
        self.product_of_numbers_label.setMinimumSize(QtCore.QSize(0, 30))
        self.product_of_numbers_label.setObjectName("product_of_numbers_label")
        self.verticalLayout.addWidget(self.product_of_numbers_label)
        self.count_of_dividers_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.count_of_dividers_label.sizePolicy().hasHeightForWidth())
        self.count_of_dividers_label.setSizePolicy(sizePolicy)
        self.count_of_dividers_label.setMinimumSize(QtCore.QSize(0, 30))
        self.count_of_dividers_label.setObjectName("count_of_devisors_label")
        self.verticalLayout.addWidget(self.count_of_dividers_label)
        self.number_dividers_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.number_dividers_label.sizePolicy().hasHeightForWidth())
        self.number_dividers_label.setSizePolicy(sizePolicy)
        self.number_dividers_label.setMinimumSize(QtCore.QSize(0, 30))
        self.number_dividers_label.setObjectName("number_divisors_label")
        self.verticalLayout.addWidget(self.number_dividers_label)
        self.factorization_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.factorization_label.sizePolicy().hasHeightForWidth())
        self.factorization_label.setSizePolicy(sizePolicy)
        self.factorization_label.setMinimumSize(QtCore.QSize(0, 30))
        self.factorization_label.setObjectName("factorization_label")
        self.verticalLayout.addWidget(self.factorization_label)
        self.is_primal_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.is_primal_label.sizePolicy().hasHeightForWidth())
        self.is_primal_label.setSizePolicy(sizePolicy)
        self.is_primal_label.setMinimumSize(QtCore.QSize(0, 30))
        self.is_primal_label.setObjectName("is_primal_label")
        self.verticalLayout.addWidget(self.is_primal_label)
        self.is_semi_primal_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.is_semi_primal_label.sizePolicy().hasHeightForWidth())
        self.is_semi_primal_label.setSizePolicy(sizePolicy)
        self.is_semi_primal_label.setMinimumSize(QtCore.QSize(0, 30))
        self.is_semi_primal_label.setObjectName("is_semi_primal_label")
        self.verticalLayout.addWidget(self.is_semi_primal_label)
        self.is_Fibbonachi_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.is_Fibbonachi_label.sizePolicy().hasHeightForWidth())
        self.is_Fibbonachi_label.setSizePolicy(sizePolicy)
        self.is_Fibbonachi_label.setMinimumSize(QtCore.QSize(0, 30))
        self.is_Fibbonachi_label.setObjectName("is_Fibbonachi_label")
        self.verticalLayout.addWidget(self.is_Fibbonachi_label)
        self.is_Katalan_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.is_Katalan_label.sizePolicy().hasHeightForWidth())
        self.is_Katalan_label.setSizePolicy(sizePolicy)
        self.is_Katalan_label.setMinimumSize(QtCore.QSize(0, 30))
        self.is_Katalan_label.setObjectName("is_Katalan_label")
        self.verticalLayout.addWidget(self.is_Katalan_label)
        self.is_Mersen_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.is_Mersen_label.sizePolicy().hasHeightForWidth())
        self.is_Mersen_label.setSizePolicy(sizePolicy)
        self.is_Mersen_label.setMinimumSize(QtCore.QSize(0, 30))
        self.is_Mersen_label.setObjectName("is_Mersen_label")
        self.verticalLayout.addWidget(self.is_Mersen_label)
        self.is_square_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.is_square_label.sizePolicy().hasHeightForWidth())
        self.is_square_label.setSizePolicy(sizePolicy)
        self.is_square_label.setMinimumSize(QtCore.QSize(0, 30))
        self.is_square_label.setObjectName("is_square_label")
        self.verticalLayout.addWidget(self.is_square_label)
        self.is_cube_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.is_cube_label.sizePolicy().hasHeightForWidth())
        self.is_cube_label.setSizePolicy(sizePolicy)
        self.is_cube_label.setMinimumSize(QtCore.QSize(0, 30))
        self.is_cube_label.setObjectName("is_cube_label")
        self.verticalLayout.addWidget(self.is_cube_label)
        self.square_root_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.square_root_label.sizePolicy().hasHeightForWidth())
        self.square_root_label.setSizePolicy(sizePolicy)
        self.square_root_label.setMinimumSize(QtCore.QSize(0, 30))
        self.square_root_label.setObjectName("square_root_label")
        self.verticalLayout.addWidget(self.square_root_label)
        self.cubic_root_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.cubic_root_label.setMinimumSize(QtCore.QSize(0, 30))
        self.cubic_root_label.setObjectName("cubic_root_label")
        self.verticalLayout.addWidget(self.cubic_root_label)
        self.sin_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.sin_label.setMinimumSize(QtCore.QSize(0, 30))
        self.sin_label.setObjectName("sin_label")
        self.verticalLayout.addWidget(self.sin_label)
        self.cos_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.cos_label.setMinimumSize(QtCore.QSize(0, 30))
        self.cos_label.setObjectName("cos_label")
        self.verticalLayout.addWidget(self.cos_label)
        self.tan_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.tan_label.setMinimumSize(QtCore.QSize(0, 30))
        self.tan_label.setObjectName("tan_label")
        self.verticalLayout.addWidget(self.tan_label)
        self.ctg_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.ctg_label.setMinimumSize(QtCore.QSize(0, 30))
        self.ctg_label.setObjectName("ctg_label")
        self.verticalLayout.addWidget(self.ctg_label)
        self.decimal_logarithm_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.decimal_logarithm_label.setMinimumSize(QtCore.QSize(0, 30))
        self.decimal_logarithm_label.setObjectName("decimal_logarithm_label")
        self.verticalLayout.addWidget(self.decimal_logarithm_label)
        self.natural_logarithm_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.natural_logarithm_label.setMinimumSize(QtCore.QSize(0, 30))
        self.natural_logarithm_label.setObjectName("natural_logarithm_label")
        self.verticalLayout.addWidget(self.natural_logarithm_label)
        self.bin_view_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.bin_view_label.setMinimumSize(QtCore.QSize(0, 30))
        self.bin_view_label.setObjectName("bin_view_label")
        self.verticalLayout.addWidget(self.bin_view_label)
        self.oct_view_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.oct_view_label.setMinimumSize(QtCore.QSize(0, 30))
        self.oct_view_label.setObjectName("oct_view_label")
        self.verticalLayout.addWidget(self.oct_view_label)
        self.hex_view_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.hex_view_label.setMinimumSize(QtCore.QSize(0, 30))
        self.hex_view_label.setObjectName("hex_view_label")
        self.verticalLayout.addWidget(self.hex_view_label)
        self.max_number_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.max_number_label.setMinimumSize(QtCore.QSize(0, 30))
        self.max_number_label.setObjectName("max_number_label")
        self.verticalLayout.addWidget(self.max_number_label)
        self.min_number_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.min_number_label.setMinimumSize(QtCore.QSize(0, 30))
        self.min_number_label.setObjectName("min_number_label")
        self.verticalLayout.addWidget(self.min_number_label)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.get_result_btn.setText(_translate("Form", "Рассчитать"))
        self.label.setText(_translate("Form", "Введите натуральное число, <=10^7"))
        self.count_of_numbers_label.setText(_translate("Form", "Количество цифр: "))
        self.amount_of_numbers_label.setText(_translate("Form", "Сумма цифр: "))
        self.product_of_numbers_label.setText(_translate("Form", "Произведение цифр(без учета 0): "))
        self.count_of_dividers_label.setText(_translate("Form", "Количество делителей: "))
        self.number_dividers_label.setText(_translate("Form", "Все делители числа: "))
        self.factorization_label.setText(_translate("Form", "Факторизация: "))
        self.is_primal_label.setText(_translate("Form", "Простое ли число: "))
        self.is_semi_primal_label.setText(_translate("Form", "Полупростое ли число: "))
        self.is_Fibbonachi_label.setText(_translate("Form", "Число Фибоначчи: "))
        self.is_Katalan_label.setText(_translate("Form", "Число Каталана: "))
        self.is_Mersen_label.setText(_translate("Form", "Число Мерсена: "))
        self.is_square_label.setText(_translate("Form", "Полный квадрат: "))
        self.is_cube_label.setText(_translate("Form", "Полный куб: "))
        self.square_root_label.setText(_translate("Form", "Квадратный корень: "))
        self.cubic_root_label.setText(_translate("Form", "Кубический корень: "))
        self.sin_label.setText(_translate("Form", "Синус (из градусов): "))
        self.cos_label.setText(_translate("Form", "Косниус (из градусов): "))
        self.tan_label.setText(_translate("Form", "Тангенс (из градусов): "))
        self.ctg_label.setText(_translate("Form", "Котангенс (из градусов): "))
        self.decimal_logarithm_label.setText(_translate("Form", "Десятичный логарифм: "))
        self.natural_logarithm_label.setText(_translate("Form", "Натуральный логарифм: "))
        self.bin_view_label.setText(_translate("Form", "Двоичный вид: "))
        self.oct_view_label.setText(_translate("Form", "Восьмеричный вид: "))
        self.hex_view_label.setText(_translate("Form", "Шестнадцатеричый вид: "))
        self.max_number_label.setText(_translate("Form", "Наибольшая цифра: "))
        self.min_number_label.setText(_translate("Form", "Наименьшая цифра: "))

    def connecting(self):
        self.get_result_btn.clicked.connect(self.write_number)

    def write_number(self):
        try:
            self.number = Number(self.lineEdit.text())
            if self.last_number != self.lineEdit.text():
                self.last_number = self.lineEdit.text()
                self.calculate_result()

        except NotNaturalNumberError:
            button = QtWidgets.QMessageBox.critical(self, 'Ошибка!', 'Вы ввели не натуральное число!',
                                                    buttons=QtWidgets.QMessageBox.StandardButton.Close,
                                                    defaultButton=QtWidgets.QMessageBox.StandardButton.Close)
        except ToBigNumber:
            button = QtWidgets.QMessageBox.critical(self, 'Ошибка!', 'Вы ввели слишком большое число!',
                                                    buttons=QtWidgets.QMessageBox.StandardButton.Close,
                                                    defaultButton=QtWidgets.QMessageBox.StandardButton.Close)
        except ValueError:
            button = QtWidgets.QMessageBox.critical(self, 'Ошибка!', 'Вы ввели не число!',
                                                    buttons=QtWidgets.QMessageBox.StandardButton.Close,
                                                    defaultButton=QtWidgets.QMessageBox.StandardButton.Close)

    def base_texts(self):
        self.count_of_numbers_label_text = self.count_of_numbers_label.text()
        self.amount_of_numbers_label_text = self.amount_of_numbers_label.text()
        self.product_of_numbers_label_text = self.product_of_numbers_label.text()
        self.count_of_dividers_label_text = self.count_of_dividers_label.text()
        self.number_dividers_label_text = self.number_dividers_label.text()
        self.factorization_label_text = self.factorization_label.text()
        self.is_primal_label_text = self.is_primal_label.text()
        self.is_semi_primal_label_text = self.is_semi_primal_label.text()
        self.is_Fibbonachi_label_text = self.is_Fibbonachi_label.text()
        self.is_Katalan_label_text = self.is_Katalan_label.text()
        self.is_Mersen_label_text = self.is_Mersen_label.text()
        self.is_square_label_text = self.is_square_label.text()
        self.is_cube_label_text = self.is_cube_label.text()
        self.square_root_label_text = self.square_root_label.text()
        self.cubic_root_label_text = self.cubic_root_label.text()
        self.sin_label_text = self.sin_label.text()
        self.cos_label_text = self.cos_label.text()
        self.tan_label_text = self.tan_label.text()
        self.ctg_label_text = self.ctg_label.text()
        self.decimal_logarithm_label_text = self.decimal_logarithm_label.text()
        self.natural_logarithm_label_text = self.natural_logarithm_label.text()
        self.bin_view_label_text = self.bin_view_label.text()
        self.oct_view_label_text = self.oct_view_label.text()
        self.hex_view_label_text = self.hex_view_label.text()
        self.max_number_label_text = self.max_number_label.text()
        self.min_number_label_text = self.min_number_label.text()

    def calculate_result(self):
        self.count_of_numbers_label.setText(self.count_of_numbers_label_text + self.number.count_of_numbers())
        self.amount_of_numbers_label.setText(self.amount_of_numbers_label_text + self.number.amount_of_numbers())
        self.product_of_numbers_label.setText(self.product_of_numbers_label_text + self.number.product_of_number())
        self.count_of_dividers_label.setText(self.count_of_dividers_label_text + self.number.dividers()[2])
        self.number_dividers_label.setText(self.number_dividers_label_text + self.number.dividers()[1])
        self.factorization_label.setText(self.factorization_label_text + self.number.dividers()[0])
        self.is_primal_label.setText(self.is_primal_label_text + self.number.dividers()[3])
        self.is_semi_primal_label.setText(self.is_semi_primal_label_text + self.number.dividers()[4])
        self.is_Fibbonachi_label.setText(self.is_Fibbonachi_label_text + self.number.is_fibonacci())
        self.is_Katalan_label.setText(self.is_Katalan_label_text + self.number.is_katalan())
        self.is_Mersen_label.setText(self.is_Mersen_label_text + self.number.is_mersen())
        self.is_square_label.setText(self.is_square_label_text + self.number.is_square())
        self.is_cube_label.setText(self.is_cube_label_text + self.number.is_cube())
        self.square_root_label.setText(self.square_root_label_text + self.number.square_root())
        self.cubic_root_label.setText(self.cubic_root_label_text + self.number.cubic_root())
        self.sin_label.setText(self.sin_label_text + self.number.sin())
        self.cos_label.setText(self.cos_label_text + self.number.cos())
        self.tan_label.setText(self.tan_label_text + self.number.tan())
        self.ctg_label.setText(self.ctg_label_text + self.number.ctg())
        self.decimal_logarithm_label.setText(self.decimal_logarithm_label_text + self.number.decimal_logarithm())
        self.natural_logarithm_label.setText(self.natural_logarithm_label_text + self.number.natural_logarithm())
        self.bin_view_label.setText(self.bin_view_label_text + self.number.bin_view())
        self.oct_view_label.setText(self.oct_view_label_text + self.number.oct_view())
        self.hex_view_label.setText(self.hex_view_label_text + self.number.hex_view())
        self.max_number_label.setText(self.max_number_label_text + self.number.max_number())
        self.min_number_label.setText(self.min_number_label_text + self.number.min_number())
